ARG IMAGE_VERSION
FROM nvcr.io/nvidia/cuda:${IMAGE_VERSION}-devel-ubuntu22.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y cmake intel-mkl-full ninja-build python3 git python3-pip && \
    apt-get install -y numactl libibverbs-dev ibverbs-utils && \
    apt-get install -y nsight-systems-2024.2.3 && \
    apt-get install -y libgsl0-dev

ENV C_INCLUDE_PATH=/usr/include/mkl:$C_INCLUDE_DIR
ENV CPLUS_INCLUDE_PATH=/usr/include/mkl:$CPLUS_INCLUDE_DIR

# star-h calls python by name
RUN ln -s /usr/bin/python3 /usr/bin/python

# some useful scripts from mlperf
RUN pip install --ignore-installed "git+https://github.com/NVIDIA/mlperf-common.git"

# copy source code
COPY CMakeLists.txt /opt/hicma-x-dev/CMakeLists.txt
COPY LICENSE /opt/hicma-x-dev/LICENSE
COPY README.md /opt/hicma-x-dev/README.md
COPY RELEASE.md /opt/hicma-x-dev/RELEASE.md
COPY VERSION.txt /opt/hicma-x-dev/VERSION.txt
COPY cmake_modules /opt/hicma-x-dev/cmake_modules
COPY data /opt/hicma-x-dev/data
COPY dplasma /opt/hicma-x-dev/dplasma
COPY hcore /opt/hicma-x-dev/hcore
COPY hicma_parsec /opt/hicma-x-dev/hicma_parsec
COPY scripts /opt/hicma-x-dev/scripts
COPY stars-h /opt/hicma-x-dev/stars-h
COPY tools /opt/hicma-x-dev/tools
ENV HICMA_ROOT /opt/hicma-x-dev

# get NVTX:
RUN cd ${HICMA_ROOT} && git clone https://github.com/NVIDIA/NVTX.git && \
    cd hicma_parsec && ln -s ../NVTX NVTX

# install stars-h
RUN ulimit -s 8388608 && \
    cd ${HICMA_ROOT}/stars-h && \
    ln -s ../NVTX NVTX && \
    mkdir -p build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/installdir -DMPI=OFF -DOPENMP=ON -DSTARPU=ON -DEXAMPLES=OFF -DTESTING=OFF -DBUILD_SHARED_LIBS=ON -DGSL=OFF && \
    make -j 8 && make  install && \
    echo "export PKG_CONFIG_PATH=${HICMA_ROOT}/stars-h/build/installdir/lib/pkgconfig:\$PKG_CONFIG_PATH" >> ${HICMA_ROOT}/env_hicma_parsec.sh
ENV PKG_CONFIG_PATH ${HICMA_ROOT}/stars-h/build/installdir/lib/pkgconfig:${PKG_CONFIG_PATH}


# install hcore
RUN ulimit -s 8388608 && \
    cd ${HICMA_ROOT}/hcore && mkdir -p build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/installdir && \
    make -j 8 && make install && \
    echo "export PKG_CONFIG_PATH=${HICMA_ROOT}/hcore/build/installdir/lib/pkgconfig:\$PKG_CONFIG_PATH" >> ${HICMA_ROOT}/env_hicma_parsec.sh
ENV PKG_CONFIG_PATH=${HICMA_ROOT}/hcore/build/installdir/lib/pkgconfig:${PKG_CONFIG_PATH}

# install hicma-x
RUN cd ${HICMA_ROOT} && mkdir -p build && cd build && \
    cmake .. \
    	  -DCMAKE_BUILD_TYPE="Release" \
	  -DCMAKE_C_FLAGS="-DGENE=1" \
	  -DCMAKE_INSTALL_PREFIX=`pwd`/installdir \
	  -DDPLASMA_PRECISIONS="s;d" \
	  -DBUILD_SHARED_LIBS=ON \
	  -DPARSEC_GPU_WITH_CUDA=ON \
	  -DPARSEC_HAVE_DEV_CUDA_SUPPORT=ON \
	  -DBLA_VENDOR=Intel10_64lp_seq \
	  -DCMAKE_INSTALL_PREFIX=`pwd`/installdir \
	  -G Ninja \
	  -DPARSEC_GPU_WITH_HIP=OFF \
	  -DPARSEC_HAVE_DEV_HIP_SUPPORT=OFF \
	  -DPARSEC_MAX_DEP_OUT_COUNT=16

RUN cd ${HICMA_ROOT}/build && ninja -v

#RUN cd /opt/hicma-x-dev && \
#    rm -rf stars-h/build && \
#    rm -rf hcore/build && \
#    rm -rf build \
#    bash tools/install_leonardo_no_gsl.sh
