#starsh
git clone https://github.com/SAbdulah/stars-h.git
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install -DMPI=OFF -DOPENMP=OFF -DSTARPU=OFF -DGSL=OFF
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install -DBUILD_SHARED_LIBS=ON -DMPI=OFF -DOPENMP=OFF -DSTARPU=OFF -DGSL=OFF
CFLAGS=-fPIC CXXFLAGS=-fPIC cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install -DBUILD_SHARED_LIBS=ON -DMPI=OFF -DOPENMP=OFF -DSTARPU=OFF -DGSL=OFF
#hcore
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install/
#hicma-x
cmake .. -DDPLASMA_PRECISIONS="s;d" -DBUILD_SHARED_LIBS=ON -DPARSEC_WITH_HEADER_FILES=ON -DPARSEC_WITH_DEVEL_HEADERS=ON  -DPARSEC_ATOMIC_USE_GCC_32_BUILTINS_EXITCODE=0 -DPARSEC_ATOMIC_USE_GCC_64_BUILTINS_EXITCODE=0 -DPARSEC_ATOMIC_USE_GCC_128_BUILTINS_EXITCODE=0 -DPARSEC_GPU_WITH_CUDA=OFF -DPARSEC_HAVE_DEV_CUDA_SUPPORT=off -DCMAKE_BUILD_TYPE=Release  -DPARSEC_DIST_COLLECTIVES=ON
#hicma-x-mp-gpu
cmake .. -DDPLASMA_PRECISIONS="s;d" -DBUILD_SHARED_LIBS=ON -DPARSEC_WITH_HEADER_FILES=ON -DPARSEC_WITH_DEVEL_HEADERS=ON  -DPARSEC_ATOMIC_USE_GCC_32_BUILTINS_EXITCODE=0 -DPARSEC_ATOMIC_USE_GCC_64_BUILTINS_EXITCODE=0 -DPARSEC_ATOMIC_USE_GCC_128_BUILTINS_EXITCODE=0 -DPARSEC_GPU_WITH_CUDA=ON -DPARSEC_HAVE_DEV_CUDA_SUPPORT=ON -DCMAKE_BUILD_TYPE=Release -DPARSEC_DIST_COLLECTIVES=ON -DHiCMA_USE_CUDA=ON
#starsh2
make .. -DCMAKE_INSTALL_PREFIX=$PWD/install -DECRC_VERBOSE_FIND_PACKAGE=ON -DMKL=ON -DBLAS_LIBRARIES="-Wl,--no-as-needed;-L${MKLROOT}/lib;-lmkl_intel_lp64;-lmkl_core;-lmkl_sequential;-lpthread;-lm;-ldl" -DBLAS_COMPILER_FLAGS="-m64;-I${MKLROOT}/include" -DLAPACK_LIBRARIES="-Wl,--no-as-needed;-L${MKLROOT}/lib;-lmkl_intel_lp64;-lmkl_core;-lmkl_sequential;-lpthread;-lm;-ldl" -DCBLAS_DIR="${MKLROOT}" -DLAPACKE_DIR="${MKLROOT}" -DTMG_DIR="${MKLROOT}" -DCMAKE_C_FLAGS=-DMKL -DMPI=OFF -DOPENMP=OFF -DSTARPU=OFF -DGSL=OFF
